### ISSUE TITLE
restructure thread pages

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#15]
degree programs, food services, campus security, campus events, commuting

**Comment by creighton-gorai** [comment]
Note: This issue in under branch named issue-07

**Comment by creighton-gorai** [comment]
Each page should have:
- Title
- Submit button
- Defaulted 10 posts from users
- Title is clickable to Topic page
- 1 posts has Title, Posted by, Time posted, # of comments in post

**Comment by creighton-gorai** [comment]
Thread pages remock-up is complete only need to:
- fill collection with 10 posts into each thread category
- clickable title
- each clickable topic has Title, Posted by, Time Posted, # of comments
