### ISSUE TITLE
update menu/nav bar to have new features

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#18]
- Edit profile button

- Do work for this issue in a branch named 'issue-18'

**Comment by creighton-gorai** [comment]
- Add a home page link
- Add dropdown for different thread sections (Ex. Degree, Commute, Food, etc....)
- Take away clickability of "UHEssentials" button to home page (Maybe reroute to landing page?)
- (Optional) Add gradient or different design to make header look more appealing
