### ISSUE TITLE
implement collection for topics

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#19]
- Do work for this issue in a branch named 'issue-19'

**Comment by creighton-gorai** [comment]
Create a template for thread page.

**Comment by creighton-gorai** [comment]
Collection of one thread will hold:
ID:
Username:
Time posted:
Tag:

**Comment by creighton-gorai** [comment]
There will be 2 or more types of methods working to implement this:
1) creating individual submit pages for each thread
2) one collection which saves all and sorts into different threads
