### ISSUE TITLE
implement a topic page

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#21]
- Do work for this issue in a branch named 'issue-21'
- Create implementable Topic page
Layout: 
- Title
- Posted By
- Time Posted by
- Tag (Thread section it belongs to)
- Information
- Comments

**Comment by creighton-gorai** [comment]
This considers:
Deleting social media items
Create dropdowns for sections:
     Standing: Student,Professor,Faculty/Staff
     Gender: Male, Female, Other
     Campus Location: Full name of College (Abbreviation)

**Comment by creighton-gorai** [comment]
- submitting/updating profile works
- radio check box for agreeing to terms 
- Create dropdowns for sections:
-- Standing: Student,Professor,Faculty/Staff
-- Gender: Male, Female, Other
-- Campus Location: Full name of College (Abbreviation)

**Comment by creighton-gorai** [comment]
Mock ups for example
