### ISSUE TITLE
update Profile page form 

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#23]
- Do work for this issue in a branch named 'issue-23'
- submitting/updating profile works
- remove radio check box for agreeing to terms 
- Create/fix dropdown for
-- Campus Location: Full name of College (Abbreviation)

**Comment by creighton-gorai** [comment]
- Take away terms/condition
- After submission of profile form link to home page
- implement standing collection (dropdown)

**Comment by creighton-gorai** [comment]
- Redirection to home page?
- Find how to put campus tag instead of commas
