### ISSUE TITLE
mockup profile page

### ISSUE THREAD

**Issue by aprilbala** [uhessentials/uhessentials#3]
- Create a pencil and paper mockup for the profile page. Here is a sketch:
![profilepage](https://user-images.githubusercontent.com/31198066/32624661-fd2a4c00-c52d-11e7-8f15-88e996a2d463.jpg)
- Create an HTML mockup of the sketch made. 
- Do work for this issue in a branch named '_**issue-03**_'

**Comment by aprilbala** [comment]
Finished result. Changes to page may be made in the future.
<img width="885" alt="profile-page-html" src="https://user-images.githubusercontent.com/31198066/33150744-ff91103c-cf78-11e7-996d-7b21398e436f.png">

**Comment by kpaahana** [comment]
👍
